apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-probe-python
  labels:
    app: python-probe
spec:
  replicas: 5
  selector:
    matchLabels:
      app: python-probe

  template:
    metadata:
      labels:
        app: python-probe
    spec:
      containers:
      - name: contenedor-python
        image: josedom24/k8s-probe-python
        ports:
          - name: http-server
            containerPort: 8080
        livenessProbe:
            httpGet:
              path: /healthz
              port: http-server
            initialDelaySeconds: 1
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 2

        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3 
           